USE [4S]
GO



truncate table [dbo].[tbl_Purchasedt]
truncate table [dbo].[LedgerPayment]
truncate table [dbo].[PaymentDue]
truncate table[dbo].[Purchase]
truncate table[dbo].[PurchaseDetail]
truncate table[dbo].[PurchaseInq]
truncate table[dbo].[ReceiptVoucher]
truncate table [dbo].[tbl_issuepettyamount]
truncate table [dbo].[tbl_IssuePettyDate]
truncate table [dbo].[tbl_demand]

truncate table[dbo].[tblInvoice]
truncate table[dbo].[tblInvoiceDetail]
truncate table[dbo].[tblnInvoice]
truncate table[dbo].[tblnInvoiceDetail]
truncate table[dbo].[tblreturndetail]
truncate table [dbo].[add_product_stock]
truncate table [dbo].[AccountBalance]
truncate table [dbo].[add_product]
truncate table [dbo].[add_product_stock]
truncate table [dbo].[BankCashIn]
truncate table [dbo].[BankCashRelease]
truncate table [dbo].[BankDetail]
truncate table [dbo].[BankTransaction]
truncate table [dbo].[BCR]
truncate table [dbo].[CashIn]
truncate table [dbo].[CashRelease]
truncate table [dbo].[CashTransaction]
truncate table [dbo].[Customer]
truncate table[dbo].[ReceiveDue]
truncate table [dbo].[LedgerPayment]
truncate table [dbo].[PaymentDue]
truncate table [dbo].[LedgerReceived]
truncate table [dbo].[PI_PurchaseDetail]
truncate table [dbo].[product_cat]
truncate table [dbo].[Purchase]
truncate table [dbo].[PurchaseDetail]
truncate table [dbo].[PurchaseInq]
truncate table [dbo].[ReceiveDue]
truncate table [dbo].[tbl_DamageProduct]
truncate table [dbo].[tbl_issuepettyamount]
truncate table [dbo].[tbl_IssuePettyDate]
truncate table [dbo].[tbl_Manual]
truncate table [dbo].[tbl_payandreceive]
truncate table [dbo].[tbl_PettyCash]
truncate table [dbo].[tbl_PettyCashDetail] 
truncate table  [dbo].[tbl_tax]
truncate table [dbo].[tbl_transfer]
truncate table [dbo].[tbl_warehouse]
truncate table [dbo].[Transactions]
truncate table [dbo].[Transactionss]
truncate table  [dbo].[tbl_Delivery]
truncate table  [dbo].[tbl_DeliveryDetail]
truncate table [dbo].[tbl_DeliveryUses]
truncate table  [dbo].[tblInvoice]
truncate table  [dbo].[tblInvoiceDetail]
truncate table  [dbo].[tblnInvoice]
truncate table  [dbo].[tblnInvoiceDetail]
			    
